name: crop_planning_techm
description: A new flutter project for TechM


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.0+1
  timeline_tile: ^1.0.0
  charts_flutter: ^0.9.0
  syncfusion_flutter_calendar: ^19.1.66
  http: ^0.13.3
  json_annotation: ^3.1.1
  sqflite: ^2.0.0+2
  path_provider: ^2.0.2
  flutter_local_notifications: ^6.0.0
  timezone: ^0.7.0
  get: ^4.1.4
  shared_preferences: ^2.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  build_runner: ^1.11.1

flutter:

  uses-material-design: true


  assets:
   - images/

  fonts:
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Medium.ttf
         weight: 600
   - family: Poppins Regular
     fonts:
       - asset: fonts/Poppins-Regular.ttf
         weight: 800




