name: crop_planning_techm
description: A new flutter project for TechM


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+17
  timeline_tile: ^1.0.0
  charts_flutter: ^0.9.0
  syncfusion_flutter_calendar: ^18.4.34


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
   - images/

  fonts:
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Medium.ttf
         weight: 600
   - family: Poppins Regular
     fonts:
       - asset: fonts/Poppins-Regular.ttf
         weight: 800




